// TrackoShellExtension.idl : IDL source for Tracko.ShellExtension
//

// This file will be processed by the MIDL tool to
// produce the type library (TrackoShellExtension.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(6248DA0B-EF81-443B-98E3-73A1F673C57A),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IWatchedOverlayIcon : IDispatch{
};
[
	uuid(5DA6319F-974B-40DA-A02C-0AECDA0BAE1D),
	version(1.0),
]
library TrackoShellExtensionLib
{
	importlib("stdole2.tlb");
	[
		uuid(D729C131-4A94-4A95-B3EE-361E37BA30BE)		
	]
	coclass WatchedOverlayIcon
	{
		[default] interface IWatchedOverlayIcon;
	};
};

